#! /usr/bin/env python
# encoding: utf-8

search_path = []

if not bld.is_mkspec_platform('windows'):
    search_path = ['.']

bld.program(
    features='cxx',
    source='recoding.cpp',
    target='recoding',
    rpath=search_path,
    use=[
        'kodo_visualize',
        'kodocpp_static_includes',
        'kodoc_static',
        'SDL2'
    ])
