#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx test',
    source=bld.path.ant_glob('**/*.cpp'),
    target='kodo_visualize_tests',
    test_files=['lena.jpg'],
    use=['kodo_visualize', 'gtest'])
