#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx',
    source='visualizer.cpp',
    target='visualizer',
    use=[
        'kodo_visualize',
        'kodocpp_static_includes',
        'kodoc_static',
        'boost_system',
        'boost_program_options',
        'boost_filesystem',
        'SDL2'
    ])

bld(rule='cp ${SRC} ${TGT}', source='PressStart2P.ttf', target='font.ttf')
