#! /usr/bin/env python
# encoding: utf-8

use_flags = ['sak', 'SDL2', 'SDL2_image']

if bld.is_mkspec_platform('linux'):
    use_flags += ['PTHREAD']

bld.stlib(
    features='cxx',
    source=bld.path.ant_glob('**/*.cpp'),
    target='kodo_visualize',
    use=use_flags,
    export_includes=['..'])
